# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for MapDemo

pod 'BaiduMapKit' #百度地图SDK
#pod 'AMap3DMap', '~> 5.0.0'

pod 'AMapSearch'
pod 'AMapLocation'
pod 'AMapNavi'

  
end


target 'MapDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
